function params = set_preproc_paths(preproc_dir)


paths = ['/fmri/spm12_utils:', ...
    '/fmri/apps/spm12:', ...
    '/fmri/apps/nx3k_matlab:', ...
    '/fmri/apps/freesurfer-5.3.0/matlab/:', ...
    genpath(preproc_dir)];

addpath(paths);

params.shell_script_path = fullfile(preproc_dir,'/fmri_preproc_functions/shell_scripts/');
